function commission() {}

function makeQuote(){[
  "marketer finds client",
  "builder passes on client",
  "designer meets with client",
  "designer drafts commission and estimate",
  "design/build mentor runs work study for designer",
  "builder meets client",
  "builder corrects estimate, lists possible cuts with monetary values",
  "owner adds percentage",
  "designer negotiates quote with client",
  "designer edits final commission",
  "be honest and open and real with the client",
  "4 parties sign commission",
  "owner advances pay and materials"]}

commission([
  "Floor panel",
  "x5",
  "Cut two tracks to 48 inches",
  "Cut 4 studs to 96 inches",
  "Lay out tracks and studs, leftmost 3/4 inches inset, 12 inches, 24 inches, and 36 inches on center",
  "Crimp",
  "Lay 3/8 inches plywood, aligned with tracks",
  "Screw tracks, and 1.25 inches in from left, 12 inches, 24 inches and 36 inches on center",
  "Cut 2x3 to 96 inches",
  "Set 2x3 in right side with 5/8 inches sticking out and screw",
  "Flip and insulate",
  "Lay 1/2 inches plywood aligned with tracks",
  "Screw tracks, and along left edge, 12 inches, 24 inches, and 36 inches on center, and 1.25 inches from the right"])

commission([
  "Z-panel",
  "x5",
  "skinny 1 inches screws for 2x2s",
  "tightly threaded 3/4 inches for plywood",
  "Cut two tracks to 48 inches",
  "Cut 4 studs to 96 - 2.5 - 3/4 - 5/8 - 1.5 = 90 5/8 CORRECT",
  "Cut two 2x2s to 89 3/8 inches plus one extra",
  "Lay out studs, leftmost at 0 inches from left, then 16 inches on left edge, 32 inches on left edge, and the rightmost 1.25 inches from the right and crimp",
  "Lay 3/8 inches plywood 5/8 inches from the left and 4 5/8 inches from the bottom",
  "Screw on the right edge, and at 16 inches and 32 inches on center",
  "Screw along bottom and top tracks",
  "Flip horizontally",
  "Set a 2x2 in the plywood tab outside the leftmost stud and screw through the metal into the 2x2",
  "Stack two 2x2 on the other side, and screw the top one into the stud",
  "pull out the under 2x2",
  "Screw the plywood into the 2x2s",
  "Insulate",
  "Cut 3/8 inches ply to 96 - 2.5 - 3/8 - 3/4 = 92 3/8 inches CORRECT",
  "Lay ply 5/8 inches from left edge and aligned with the bottom track",
  "Screw on the left",
  "Screw 2.5 inches from the right, 18.5 inches, and 32.5 inches from the right"])

commission([
  "A-panel",
  "x4",
  "Cut two 2x2s to 89 3/8 inches",
  "Cut one 1x3 to 89 3/8 inches",
  "Tack a 1x3 to the left edge of the plywood, 4 5/8 inches from the bottom",
  "Set a 2x2 to the left edge of the 1x3 and screw all three together",
  "Cut 4 studs to 89 3/8",
  "Lay out studs next to the 2x2, at 16 inches on center, 32 inches on center, and 1.25 + 5/8 = 2 1/8 from the right edge",
  "Cut two tracks to 48 - 2.5 - 1.25 = 44 1/4",
  "Set tracks against the 1x3 and crimp",
  "Screw the frame into the 1x1 on right",
  "Screw a 2x2 on the outside of the leftmost stud",
  "Cut interior plywood to 48 - 3*5/8 - 1.25 - 2.5 = 42 3/8 wide and 90 3/8 inches long",
  "Insulate",
  "Lay plywood, 3/8 inches from the 1x3 and 5/8 inches from the other edge, even with the track at the bottom",
  "screw at 16 inches and 32 inches and along both edges",
  "Flip the panel",
  "Screw at 3 1/8 inches from the left, at 16 inches and 32 inches and 2.5 inches from the right edge",
  "Note: the z-panel plywood gap is 5/8, but the A-panel corner gap is only 3/8!"])
